### ISSUE TITLE
Improve Task 03 - Test the prompt in Content Safety instructions to reduce confusion

### ISSUE THREAD

**Issue by jasonhorner** [microsoft/TechExcel-Operationalize-LLMs-with-LLMOps-automation#14]
The role assignment is a bit ambigous in the document:

https://microsoft.github.io/TechExcel-Operationalize-LLMs-with-LLMOps-automation/docs/01_intro_to_llms/01_03.html

This text:
[!IMPORTANT] If you encounter an error message stating Your account does not have access to this resource, please contact your resource owner to get access, make sure to add the role assigment of Azure AI Developer to your user account and wait 10 minutes for the permission to propagate and try again.

could be improved to :

- call out that is an azure resource level RBAC Role as opposed to an entra role assignment
- It should also be noted that this requires owner rights contributor is not enough

additionally, I would include this example command to perform the assignment via cloud shell:

`az role assignment create --role "Azure AI Developer" --assignee "<upn>" --resource-group <rg-name>`

**Comment by StephanieKClark** [comment]
This has been added.
